version: "3.9"

services:
  web:
    build: .
    container_name: flask_calculator
    ports:
      - "5000:5000"
    environment:
       AWS_ACCESS_KEY_ID: test
       AWS_SECRET_ACCESS_KEY: test
       AWS_DEFAULT_REGION: us-east-1
       S3_ENDPOINT: http://host.docker.internal:4566
    